// Component catalog for the Step 3 kit.
// Each entry: id, label (EN), labelKo (KR), group, defaultText, defaultWidth (px),
//   defaultHeight (px), icon, colSpan, rowSpan
//
// defaultText: visible mock content when first dropped — participants edit by double-click.
// defaultWidth: initial card width in px on the canvas.
// defaultHeight: initial card height in px on the canvas.
// icon: emoji to visually identify the widget type.
// colSpan / rowSpan: how many grid cells the palette tile occupies (1 or 2).
//   This only affects the palette preview — canvas items use free positioning.

// Per-group colour tokens (used in ComponentCard for background / accent colour)
export const GROUP_COLORS = {
  trust: {
    bg: "rgba(99,102,241,0.08)",
    border: "rgba(99,102,241,0.25)",
    accent: "#6366f1",
    light: "#eef2ff",
    gradient: "linear-gradient(135deg, #eef2ff 0%, #e0e7ff 100%)",
  },
  vibe: {
    bg: "rgba(236,72,153,0.08)",
    border: "rgba(236,72,153,0.25)",
    accent: "#ec4899",
    light: "#fdf2f8",
    gradient: "linear-gradient(135deg, #fdf2f8 0%, #fce7f3 100%)",
  },
  social: {
    bg: "rgba(34,197,94,0.08)",
    border: "rgba(34,197,94,0.25)",
    accent: "#22c55e",
    light: "#f0fdf4",
    gradient: "linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%)",
  },
  logistics: {
    bg: "rgba(245,158,11,0.08)",
    border: "rgba(245,158,11,0.25)",
    accent: "#f59e0b",
    light: "#fffbeb",
    gradient: "linear-gradient(135deg, #fffbeb 0%, #fef3c7 100%)",
  },
  custom: {
    bg: "rgba(107,114,128,0.08)",
    border: "rgba(107,114,128,0.25)",
    accent: "#6b7280",
    light: "#f9fafb",
    gradient: "linear-gradient(135deg, #f9fafb 0%, #f3f4f6 100%)",
  },
};

export const COMPONENT_CATALOG = [
  // ─── TRUST ────────────────────────────────────────────────────────────────────
  {
    id: "rating-reviews",
    label: "Rating & Reviews",
    labelKo: "별점·리뷰수",
    group: "trust",
    icon: "⭐",
    defaultText: "★ 4.3 · 1,284 reviews",
    defaultWidth: 200,
    defaultHeight: 72,
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: "review-snippet",
    label: "Review Snippet",
    labelKo: "리뷰 발췌",
    group: "trust",
    icon: "💬",
    defaultText: "'혼자 가서 책 읽기 좋아요'",
    defaultWidth: 320,
    defaultHeight: 100,
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: "owner-reply",
    label: "Owner Reply",
    labelKo: "사장님 답변",
    group: "trust",
    icon: "🏪",
    defaultText: "💬 '답변 빠르게 해드려요' — 사장님",
    defaultWidth: 320,
    defaultHeight: 100,
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: "verified",
    label: "Verified",
    labelKo: "인증 매장",
    group: "trust",
    icon: "✅",
    defaultText: "✓ Verified",
    defaultWidth: 140,
    defaultHeight: 56,
    colSpan: 1,
    rowSpan: 1,
  },

  // ─── VIBE ─────────────────────────────────────────────────────────────────────
  {
    id: "mood-photo",
    label: "Mood Photo",
    labelKo: "분위기 사진",
    group: "vibe",
    icon: "📸",
    defaultText: "Insta-style photo",
    defaultWidth: 280,
    defaultHeight: 160,
    colSpan: 2,
    rowSpan: 2,
  },
  {
    id: "mood-tag",
    label: "Mood / Situation Tag",
    labelKo: "무드·상황 태그",
    group: "vibe",
    icon: "🏷️",
    defaultText: "조용한 · 혼자 · 데이트",
    defaultWidth: 240,
    defaultHeight: 72,
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: "music",
    label: "Music",
    labelKo: "음악",
    group: "vibe",
    icon: "🎵",
    defaultText: "🎵 Lo-fi · 잔잔",
    defaultWidth: 180,
    defaultHeight: 60,
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: "lighting",
    label: "Lighting",
    labelKo: "조명",
    group: "vibe",
    icon: "💡",
    defaultText: "💡 Warm · 어둡지 않은",
    defaultWidth: 200,
    defaultHeight: 60,
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: "outdoor-seating",
    label: "Outdoor Seating",
    labelKo: "야외석",
    group: "vibe",
    icon: "🌿",
    defaultText: "🌿 야외석 있음",
    defaultWidth: 180,
    defaultHeight: 60,
    colSpan: 1,
    rowSpan: 1,
  },

  // ─── SOCIAL ───────────────────────────────────────────────────────────────────
  {
    id: "friend-visit",
    label: "Friend Visited",
    labelKo: "친구 방문 뱃지",
    group: "social",
    icon: "👥",
    defaultText: "지수, 민준 visited",
    defaultWidth: 220,
    defaultHeight: 80,
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: "last-visit",
    label: "Last Visit Time",
    labelKo: "최근 방문 시간",
    group: "social",
    icon: "🕐",
    defaultText: "Visited 3 days ago",
    defaultWidth: 200,
    defaultHeight: 60,
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: "saved-by-friends",
    label: "Saved by Friends",
    labelKo: "친구가 저장한 곳",
    group: "social",
    icon: "💾",
    defaultText: "Saved by 4 friends",
    defaultWidth: 240,
    defaultHeight: 72,
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: "trending",
    label: "Trending",
    labelKo: "지금 핫한",
    group: "social",
    icon: "🔥",
    defaultText: "🔥 Trending this week",
    defaultWidth: 220,
    defaultHeight: 60,
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: "group-size",
    label: "Group Size",
    labelKo: "권장 인원",
    group: "social",
    icon: "👫",
    defaultText: "👥 1–4 people",
    defaultWidth: 180,
    defaultHeight: 56,
    colSpan: 1,
    rowSpan: 1,
  },

  // ─── LOGISTICS ────────────────────────────────────────────────────────────────
  {
    id: "distance",
    label: "Distance & Walk Time",
    labelKo: "거리·도보 시간",
    group: "logistics",
    icon: "📍",
    defaultText: "320m · walk 5min",
    defaultWidth: 220,
    defaultHeight: 60,
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: "waiting",
    label: "Waiting Status",
    labelKo: "웨이팅 여부",
    group: "logistics",
    icon: "⏳",
    defaultText: "No wait · 웨이팅 없음",
    defaultWidth: 200,
    defaultHeight: 60,
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: "price",
    label: "Price Range",
    labelKo: "가격대",
    group: "logistics",
    icon: "💰",
    defaultText: "₩₩ · 12–18k",
    defaultWidth: 160,
    defaultHeight: 56,
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: "operating-hours",
    label: "Operating Hours",
    labelKo: "영업 시간",
    group: "logistics",
    icon: "🕒",
    defaultText: "🕒 Open · ~22:00",
    defaultWidth: 220,
    defaultHeight: 60,
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: "reservations",
    label: "Reservations",
    labelKo: "예약 가능",
    group: "logistics",
    icon: "📅",
    defaultText: "📅 Reservations OK",
    defaultWidth: 220,
    defaultHeight: 60,
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: "parking",
    label: "Parking",
    labelKo: "주차",
    group: "logistics",
    icon: "🅿️",
    defaultText: "🅿️ 무료 주차",
    defaultWidth: 180,
    defaultHeight: 56,
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: "menu",
    label: "Menu Highlights",
    labelKo: "메뉴 하이라이트",
    group: "logistics",
    icon: "📋",
    defaultText: "📋 시그니처: 들기름 파스타",
    defaultWidth: 280,
    defaultHeight: 80,
    colSpan: 2,
    rowSpan: 1,
  },

  // ─── CUSTOM ───────────────────────────────────────────────────────────────────
  {
    id: "blank-text",
    label: "Custom Note",
    labelKo: "직접 입력",
    group: "custom",
    icon: "✏️",
    defaultText: "",
    defaultWidth: 240,
    defaultHeight: 80,
    colSpan: 2,
    rowSpan: 1,
  },
];

export const GROUP_LABELS = {
  trust: { en: "Trust", ko: "신뢰", icon: "🛡️" },
  vibe: { en: "Vibe", ko: "분위기", icon: "✨" },
  social: { en: "Social", ko: "사회적", icon: "👥" },
  logistics: { en: "Logistics", ko: "현실 정보", icon: "📦" },
  custom: { en: "Custom", ko: "직접 입력", icon: "✏️" },
};

export function findComponent(id, customComponents = []) {
  return (
    COMPONENT_CATALOG.find((c) => c.id === id) ??
    customComponents.find((c) => c.id === id)
  );
}
